delete ecosystem url github release path to original stateversion: 2

updates:

  # Enable version updates for GitHub ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
